#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import itertools
import json
import os
import re
import shlex
import stat
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

try:
    import tomllib
except Exception:  # pragma: no cover
    tomllib = None  # type: ignore


REPO_ROOT = Path(__file__).resolve().parents[2]
BASE_VREFS = (0.15, 0.30, 0.50)
PAIR_TAGS = ("15", "30", "50")
DIR_TAGS = {-1: "i", 0: "k", 1: "o"}
DIR_NAMES = {-1: "inward", 0: "keep", 1: "outward"}


class VrefSweepError(RuntimeError):
    pass


def _ts() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())


def log(msg: str) -> None:
    print(f"[{_ts()}] {msg}")


def fmt_float(v: float) -> str:
    s = f"{float(v):.6f}".rstrip("0").rstrip(".")
    return s if s else "0"


def fmt_vref_value(v: float) -> str:
    if abs(v) < 5e-7:
        return "0"
    return f"{v:+.3f}"


def vref_label(values: list[float]) -> str:
    return ",".join(fmt_vref_value(v) for v in values)


def toml_quote(s: str) -> str:
    return json.dumps(str(s))


def toml_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int) and not isinstance(v, bool):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return toml_quote(v)
    raise VrefSweepError(f"Unsupported TOML scalar type: {type(v).__name__}")


def toml_array(vs: list[Any]) -> str:
    if all(not isinstance(x, (dict, list)) for x in vs):
        return "[" + ", ".join(toml_scalar(x) for x in vs) + "]"
    raise VrefSweepError("Nested TOML arrays are not supported by this generator")


def emit_toml_table(lines: list[str], table_name: str, data: dict[str, Any]) -> None:
    lines.append(f"[{table_name}]")
    for k, v in data.items():
        if isinstance(v, dict):
            continue
        if isinstance(v, list):
            if v and all(isinstance(x, dict) for x in v):
                continue
            lines.append(f"{k} = {toml_array(v)}")
        else:
            lines.append(f"{k} = {toml_scalar(v)}")
    lines.append("")


def emit_toml_array_table(lines: list[str], table_name: str, items: list[dict[str, Any]]) -> None:
    for item in items:
        lines.append(f"[[{table_name}]]")
        for k, v in item.items():
            if isinstance(v, dict):
                raise VrefSweepError(f"Nested dict under [[{table_name}]] key {k!r} is not supported")
            if isinstance(v, list):
                lines.append(f"{k} = {toml_array(v)}")
            else:
                lines.append(f"{k} = {toml_scalar(v)}")
        lines.append("")


def dump_toml(data: dict[str, Any]) -> str:
    lines: list[str] = [
        "# Auto-generated by scripts/vref_sweep/submit_vref_sweep.py",
        "# Edit the template TOML instead of this generated file.",
        "",
    ]
    for k, v in data.items():
        if k == "cases":
            continue
        if isinstance(v, dict):
            emit_toml_table(lines, k, v)
        elif isinstance(v, list) and v and all(isinstance(x, dict) for x in v):
            emit_toml_array_table(lines, k, v)
        elif isinstance(v, list):
            lines.append(f"{k} = {toml_array(v)}")
        else:
            lines.append(f"{k} = {toml_scalar(v)}")
    cases = data.get("cases")
    if not isinstance(cases, list) or not cases:
        raise VrefSweepError("Generated TOML has no [[cases]]")
    emit_toml_array_table(lines, "cases", cases)
    return "\n".join(lines).rstrip() + "\n"


def load_template_toml(path: Path) -> dict[str, Any]:
    if tomllib is None:
        raise VrefSweepError("tomllib is unavailable; use Python >= 3.11")
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    cases = data.get("cases")
    if not isinstance(cases, list) or not cases or not isinstance(cases[0], dict):
        raise VrefSweepError("Template TOML must contain at least one [[cases]] table")
    return data


def parse_steps(expr: str) -> list[float]:
    vals: list[float] = []
    for part in str(expr).split(","):
        s = part.strip()
        if not s:
            continue
        val = float(s)
        if val <= 0:
            raise VrefSweepError(f"Step must be positive, got {val}")
        vals.append(val)
    if not vals:
        raise VrefSweepError("--steps produced no values")
    return vals


def patch_vref_line(template_cnfg: Path, out_cnfg: Path, values: list[float]) -> None:
    lines = template_cnfg.read_text(encoding="utf-8").splitlines()
    idx = None
    for i, line in enumerate(lines):
        if "VERF values" in line or "VREF values" in line:
            idx = i
            break
    if idx is None:
        if len(lines) < 34:
            raise VrefSweepError(f"Template cnfg has fewer than 34 lines: {template_cnfg}")
        idx = 33

    old = lines[idx]
    if "//" in old:
        _, comment = old.split("//", 1)
        suffix = " //" + comment.rstrip()
    else:
        suffix = ""
    left = " ".join(f"{v:.6g}" for v in values)
    lines[idx] = f"{left:<32}{suffix}"
    out_cnfg.parent.mkdir(parents=True, exist_ok=True)
    out_cnfg.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_vrefs(step: float | None, dirs: tuple[int, int, int]) -> list[float]:
    mags: list[float] = []
    for base, direction in zip(BASE_VREFS, dirs):
        delta = 0.0 if step is None else step * direction
        mag = base + delta
        if mag <= 0:
            raise VrefSweepError(f"Invalid VREF magnitude {mag} from base={base}, step={step}, dir={direction}")
        mags.append(mag)
    return [0.0, mags[0], -mags[0], mags[1], -mags[1], mags[2], -mags[2]]


def case_name_for(step: float | None, dirs: tuple[int, int, int]) -> str:
    if step is None:
        return "baseline"
    step_tag = str(int(round(step * 1000))).zfill(3)
    parts = [f"{tag}{DIR_TAGS[d]}" for tag, d in zip(PAIR_TAGS, dirs)]
    return f"s{step_tag}_" + "_".join(parts)


def iter_cases(include_baseline: bool, steps: list[float]) -> list[tuple[str, float | None, tuple[int, int, int], list[float]]]:
    out: list[tuple[str, float | None, tuple[int, int, int], list[float]]] = []
    if include_baseline:
        dirs = (0, 0, 0)
        out.append((case_name_for(None, dirs), None, dirs, make_vrefs(None, dirs)))
    for step in steps:
        for dirs in itertools.product((-1, 0, 1), repeat=3):
            if dirs == (0, 0, 0):
                continue
            name = case_name_for(step, dirs)
            out.append((name, step, dirs, make_vrefs(step, dirs)))
    return out


def build_case_toml(
    *,
    template_data: dict[str, Any],
    case_name: str,
    cnfg_path: Path,
    exe: Path,
    out_dir: Path,
    queue: str,
) -> str:
    data: dict[str, Any] = {k: v for k, v in template_data.items() if k != "cases"}
    defaults = data.get("defaults")
    if isinstance(defaults, dict):
        defaults = dict(defaults)
        # These fields are generated per VREF case. Keeping stale values in
        # [defaults] is harmless to AutoFER but makes the generated TOML unclear.
        for key in ("name", "workdir", "exe", "config", "out_dir", "log_prefix"):
            defaults.pop(key, None)
        data["defaults"] = defaults
    if queue:
        lsf = dict(data.get("lsf", {}) if isinstance(data.get("lsf"), dict) else {})
        lsf["queue"] = queue
        lsf["queue_slow"] = queue
        lsf["queue_fast"] = queue
        data["lsf"] = lsf

    base_cases = template_data.get("cases")
    if not isinstance(base_cases, list) or not base_cases or not isinstance(base_cases[0], dict):
        raise VrefSweepError("Template TOML has no valid first [[cases]]")
    case = dict(base_cases[0])
    case["name"] = case_name
    case["workdir"] = str(exe.parent.resolve())
    case["exe"] = str(exe.resolve())
    case["config"] = str(cnfg_path.resolve())
    case["out_dir"] = str((out_dir / "autofer_out" / case_name).resolve())
    case["log_prefix"] = case_name
    data["cases"] = [case]
    return dump_toml(data)


def shell_join(cmd: list[str]) -> str:
    return " ".join(shlex.quote(x) for x in cmd)


def bsub_command(*, queue: str, job_name: str, log_path: Path, python_bin: str, auto_fer_eval: Path, toml_path: Path) -> list[str]:
    cmd = ["bsub"]
    if queue:
        cmd.extend(["-q", queue])
    cmd.extend(["-J", job_name, "-o", str(log_path.resolve())])
    cmd.extend([python_bin, str(auto_fer_eval.resolve()), "adaptive", "--config", str(toml_path.resolve())])
    return cmd


def run_cmd(cmd: list[str], *, dry_run: bool) -> str:
    if dry_run:
        log(f"[dry-run] {shell_join(cmd)}")
        return ""
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, errors="replace", check=False)
    out = p.stdout or ""
    if p.returncode != 0:
        raise VrefSweepError(f"Command failed ({p.returncode}): {shell_join(cmd)}\n{out}")
    return out


def parse_args(argv: list[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate and submit parallel AutoFER VREF sweep jobs")
    ap.add_argument("--template-cnfg", default=str(REPO_ROOT / "IBEX" / "config" / "Ibex_hd_row11.cnfg"))
    ap.add_argument("--template-toml", required=True)
    ap.add_argument("--exe", required=True, help="Path to ssd_fc executable")
    ap.add_argument("--out-dir", default="output/vref_sweep")
    ap.add_argument("--auto-fer-eval", default="", help="Path to auto_fer_eval.py")
    ap.add_argument("--auto-fer-dir", default="", help="Directory containing auto_fer_eval.py and sibling helper scripts")
    ap.add_argument("--python-bin", default=sys.executable)
    ap.add_argument("--queue", default="", help="Queue for outer bsub and generated TOML [lsf] queues")
    ap.add_argument("--steps", default="0.025,0.05", help="Comma-separated common step sizes")
    ap.add_argument("--job-prefix", default="vref")
    ap.add_argument("--no-baseline", action="store_true")
    ap.add_argument("--no-submit", action="store_true", help="Generate files and submit_all.sh, but do not run bsub")
    ap.add_argument("--dry-run", action="store_true", help="Print bsub commands instead of submitting")
    ap.add_argument("--max-cases", type=int, default=0, help="Limit generated cases for smoke tests (0 = all)")
    return ap.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    template_cnfg = Path(args.template_cnfg).expanduser().resolve()
    template_toml = Path(args.template_toml).expanduser().resolve()
    exe = Path(args.exe).expanduser().resolve()
    if str(args.auto_fer_dir).strip():
        auto_fer_dir = Path(args.auto_fer_dir).expanduser().resolve()
        auto_fer_eval = auto_fer_dir / "auto_fer_eval.py"
    elif str(args.auto_fer_eval).strip():
        auto_fer_eval = Path(args.auto_fer_eval).expanduser().resolve()
        auto_fer_dir = auto_fer_eval.parent
    else:
        auto_fer_dir = (REPO_ROOT / "scripts" / "auto_fer_eval").resolve()
        auto_fer_eval = auto_fer_dir / "auto_fer_eval.py"
    out_dir = Path(args.out_dir).expanduser().resolve()

    if not template_cnfg.exists():
        raise VrefSweepError(f"template cnfg not found: {template_cnfg}")
    if not template_toml.exists():
        raise VrefSweepError(f"template TOML not found: {template_toml}")
    if not exe.exists():
        raise VrefSweepError(f"exe not found: {exe}")
    if exe.name != "ssd_fc":
        raise VrefSweepError(f"--exe basename must be ssd_fc, got: {exe.name}")
    if not auto_fer_eval.exists():
        raise VrefSweepError(f"auto_fer_eval not found: {auto_fer_eval}")
    missing_helpers = [
        name
        for name in ("log_parser.py", "manifest.py", "planner.py", "executors.py", "job_db.py", "xlsx_min.py")
        if not (auto_fer_eval.parent / name).exists()
    ]
    if missing_helpers:
        raise VrefSweepError(
            f"auto_fer_eval helper script(s) missing under {auto_fer_eval.parent}: {', '.join(missing_helpers)}"
        )

    template_data = load_template_toml(template_toml)
    cases = iter_cases(include_baseline=not args.no_baseline, steps=parse_steps(args.steps))
    if int(args.max_cases) > 0:
        cases = cases[: int(args.max_cases)]

    cfg_dir = out_dir / "configs"
    toml_dir = out_dir / "toml"
    log_dir = out_dir / "logs"
    for d in (cfg_dir, toml_dir, log_dir, out_dir / "autofer_out"):
        d.mkdir(parents=True, exist_ok=True)

    cases_csv = out_dir / "cases.csv"
    commands_sh = out_dir / "submit_all.sh"
    jobs_csv = out_dir / "submitted_jobs.csv"
    commands: list[list[str]] = []

    with cases_csv.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(
            [
                "case_name",
                "step",
                "dir_015",
                "dir_030",
                "dir_050",
                "vref_values",
                "vref_label",
                "config",
                "toml",
                "autofer_out_dir",
                "progress_xlsx",
            ]
        )
        for case_name, step, dirs, vrefs in cases:
            cnfg_path = cfg_dir / f"{case_name}.cnfg"
            toml_path = toml_dir / f"{case_name}.toml"
            patch_vref_line(template_cnfg, cnfg_path, vrefs)
            toml_text = build_case_toml(
                template_data=template_data,
                case_name=case_name,
                cnfg_path=cnfg_path,
                exe=exe,
                out_dir=out_dir,
                queue=str(args.queue).strip(),
            )
            toml_path.write_text(toml_text, encoding="utf-8")
            progress_xlsx = out_dir / "autofer_out" / case_name / f"{case_name}_progress.xlsx"
            writer.writerow(
                [
                    case_name,
                    "" if step is None else fmt_float(step),
                    DIR_NAMES[dirs[0]],
                    DIR_NAMES[dirs[1]],
                    DIR_NAMES[dirs[2]],
                    " ".join(fmt_float(x) for x in vrefs),
                    vref_label(vrefs),
                    str(cnfg_path.resolve()),
                    str(toml_path.resolve()),
                    str((out_dir / "autofer_out" / case_name).resolve()),
                    str(progress_xlsx.resolve()),
                ]
            )
            commands.append(
                bsub_command(
                    queue=str(args.queue).strip(),
                    job_name=f"{args.job_prefix}_{case_name}",
                    log_path=log_dir / f"{case_name}.autofer.log",
                    python_bin=str(args.python_bin),
                    auto_fer_eval=auto_fer_eval,
                    toml_path=toml_path,
                )
            )

    with commands_sh.open("w", encoding="utf-8") as fh:
        fh.write("#!/usr/bin/env bash\nset -euo pipefail\n\n")
        for cmd in commands:
            fh.write(shell_join(cmd) + "\n")
    mode = commands_sh.stat().st_mode
    commands_sh.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    log(f"generated cases: {len(cases)}")
    log(f"wrote cases metadata: {cases_csv}")
    log(f"wrote submit script: {commands_sh}")

    if args.no_submit:
        log("--no-submit set; generation complete")
        return 0

    with jobs_csv.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["case_name", "job_name", "bsub_output"])
        for (case_name, _, _, _), cmd in zip(cases, commands):
            out = run_cmd(cmd, dry_run=bool(args.dry_run))
            writer.writerow([case_name, f"{args.job_prefix}_{case_name}", out.strip()])
            if out.strip():
                log(f"submitted {case_name}: {out.strip()}")
    log(f"wrote submission log: {jobs_csv}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except VrefSweepError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        raise SystemExit(1)
